### ISSUE TITLE
Can not run the example on MacOsx

### ISSUE THREAD

**Issue by mrlove** [newrelic/centurion#101]
When i trigger the following cmd on my console:
bundle exec centurion -p radio-radio -e production -a deploy

I get the following output which is really senseless to me: (some one an idea?)
** Invoke environment:production (first_time)
** Invoke environment:common (first_time)
** Execute environment:common
** Execute environment:production
** Invoke deploy (first_time)
** Execute deploy
** Invoke deploy:get_image (first_time)
** Execute deploy:get_image
** Invoke deploy:pull_image (first_time)
** Execute deploy:pull_image
I, [2015-03-14T15:15:57.561132 #2996]  INFO -- : Fetching image redis:latest IN PARALLEL

I, [2015-03-14T15:15:57.566596 #2996]  INFO -- : Using CLI to pull
/Library/Ruby/Gems/2.0.0/gems/centurion-1.5.1/lib/centurion/logging.rb:43:in `popen': No such file or directory - docker (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/centurion-1.5.1/lib/centurion/logging.rb:43:in `run_without_echo'
	from /Library/Ruby/Gems/2.0.0/gems/centurion-1.5.1/lib/centurion/logging.rb:25:in `echo'
	from /Library/Ruby/Gems/2.0.0/gems/centurion-1.5.1/lib/centurion/docker_via_cli.rb:17:in `pull'
	from /Library/Ruby/Gems/2.0.0/gems/centurion-1.5.1/lib/tasks/deploy.rake:195:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/centurion-1.5.1/lib/centurion/docker_server_group.rb:28:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/centurion-1.5.1/lib/centurion/docker_server_group.rb:28:in `block (2 levels) in each_in_parallel'

**Comment by mrlove** [comment]
When i trigger `bundle exec centurion -p radio-radio -e production -a list`
I get the following output:

** Invoke environment:production (first_time)
** Invoke environment:common (first_time)
** Execute environment:common
** Execute environment:production
** Invoke list (first_time)
** Execute list
** Invoke list:tags (first_time)
** Execute list:tags
GET: "https://registry.hub.docker.com/v1/repositories/redis/tags"
	latest	-> 53b6894a
	2	-> 868be653
	2.6	-> a2c17d45
	2.6.17	-> a2c17d45
	2.8	-> 868be653
	2.8.10	-> 9554c310
	2.8.11	-> fb968d8e
	2.8.12	-> a2f8e595
	2.8.13	-> 1e665a02
	2.8.14	-> 9a809f46
	2.8.15	-> b1985912
	2.8.16	-> 7c66279c
	2.8.17	-> dad71287
	2.8.18	-> c1ecf7e6
	2.8.19	-> 868be653
	2.8.6	-> 6064dc06
	2.8.7	-> 818c4318
	2.8.8	-> acf48e3e
	2.8.9	-> e938c5d0

** Invoke list:running_containers (first_time)
** Execute list:running_containers
I, [2015-03-14T15:18:15.991699 #3014]  INFO -- : ----- Connecting to Docker on 172.28.128.3 -----

I, [2015-03-14T15:18:15.994738 #3014]  INFO -- : ----- Connecting to Docker on 172.28.128.4 -----

I, [2015-03-14T15:18:15.996880 #3014]  INFO -- : ----- Connecting to Docker on 172.28.128.5 -----

**Comment by relistan** [comment]
Looks like you don't have the `docker` CLI tools installed?

**Comment by mrlove** [comment]
Sure, i am aware of that, i am using mac... maybe i give it a try again in some vagrant box
