### ISSUE TITLE
Volumes from "parent" problem.

### ISSUE THREAD

**Issue by subicura** [newrelic/centurion#117]
Hello!

I have error while deploy with centurion.
`Could not apply volumes of non-existent container "parent"`
So I comment this line (https://github.com/newrelic/centurion/blob/master/lib/centurion/service.rb#L95) and problem resolved.

I'm wondering why "VolumesFrom" option has default value "parent".
Is it OK? If I remove VolumesFrom default option?

* docker version - 1.6.2

**Comment by kremso** [comment]
Hi @subicura, this seems like a backward-incompatible change in docker, at least that's what relistan suggests here https://github.com/newrelic/centurion/pull/108#issuecomment-98514185.

We hit this problem too, on docker 1.6 and removed the `VolumesFrom` directive and nothing bad happened _yet_. I can't find any information on what that is and why (and if) it has been deprecated though.

**Comment by subicura** [comment]
@kremso Thank you for your comment! It seems 1.6 problem.

**Comment by relistan** [comment]
Thanks @subicura @kremso. Looks like we need to figure out what's wrong with 1.6 in this area. They broke the versioned API again it seems.

**Comment by relistan** [comment]
Merged from @MarkBorcherding's fix-docker-1.6 branch. Tested against 1.5 as well and it's fine. Further back than that might experience an issue.
