### ISSUE TITLE
trouble deploying to Docker host (centurion = 1.7.2, Docker host = 1.7.1)

### ISSUE THREAD

**Issue by jsheth7** [newrelic/centurion#131]
Hello,

I'm having the following issue when I deploy with centurion 1.7.2, to an Ubuntu 14 Docker host, running Docker 1.7.1, and created using docker-machine).

I'm on MacOSX 10.10.4, and have ruby version 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

```
/Users/{username}/bin/centurion/lib/centurion/docker_via_api.rb:33:in `inspect_image': #<Excon::Response:0x007fe7d20986b8 @data={:body=>"client is too old, minimum supported API version is 1.12, please upgrade your client to a newer version\n", :headers=>{"Content-Type"=>"text/plain; charset=utf-8", "Date"=>"Thu, 30 Jul 2015 21:21:39 GMT", "Content-Length"=>"104"}, :status=>400, :status_line=>"HTTP/1.1 400 Bad Request\r\n", :reason_phrase=>"Bad Request", :remote_ip=>"{ip address}", :local_port=>61525, :local_address=>"{ip address}"}, @body="client is too old, minimum supported API version is 1.12, please upgrade your client to a newer version\n", @headers={"Content-Type"=>"text/plain; charset=utf-8", "Date"=>"Thu, 30 Jul 2015 21:21:39 GMT", "Content-Length"=>"104"}, @status=400, @remote_ip="10.132.8.78", @local_port=61525, @local_address="10.130.200.109"> (RuntimeError)
```

Looking at the relevant bits of code in docker_via_api.rb on line 33, I see:

```
def inspect_image(image, tag = "latest")
    repository = "#{image}:#{tag}"
    path       = "/v1.7/images/#{repository}/json"

    response = Excon.get(
      @base_uri + path,
      tls_excon_arguments.merge(:headers => {'Accept' => 'application/json'})
    )
    #NOTE: It fails here -
    raise response.inspect unless response.status == 200
    JSON.load(response.body)
  end
```

It seems like the Excon library is receiving an exception from the docker server, because the docker server is looking for a user agent. Has anyone else seen this issue, and if so, how can it be fixed?

Thank you.

**Comment by kremso** [comment]
@jsheth7 It seems that docker 1.7 deprecated some of the APIs that centurion uses. If you are in a hurry you can downgrade to docker 1.6 (which works with centurion).

**Comment by jsheth7** [comment]
Hi @kremso,
thanks for your note. I will try it with a Docker 1.6 host.
@relistan  - Do you know if / when Docker 1.7 support is planned for Centurion ?

**Comment by relistan** [comment]
@jsheth7 we're not yet running 1.7 or higher in production and haven't seen the issues you mention. We'll likely not move to 1.7 or 1.8 due to production issues with both releases. We'd welcome a PR around any issues with the current Docker builds. Thanks!

**Comment by tedkulp** [comment]
Unfortunately CoreOS stable builds have all moved to Docker 1.7 now, so Centurion is kind of a non-starter at this point. I'm going to see if I can carve some time in my next sprint to try and fix up the issues and send a PR if possible.

**Comment by relistan** [comment]
@tedkulp thanks, we'll likely move to 1.7 in the near future as well, now that it has a stable patch level, and would love a contribution there if you have the time.

**Comment by jlee-sazze** [comment]
I got the same error on machines running docker 1.8.2.
I resolved the issue by changing all the api versions from end points such as
`path       = "/v1.12/images/#{repository}/json"`
I wonder why api version is hard coded.
