### ISSUE TITLE
Exporting variables locallay

### ISSUE THREAD

**Issue by frankywahl** [newrelic/centurion#140]
Great work with the release of 1.8

With the new feature of 1.8
https://github.com/newrelic/centurion#exporting-environment-variables-locally

I can see this being a high risk. For instance, exporting production, forgetting they exported, and run `rake db:drop` or something else quite damaging. People dealing with multiple windows - panes - ... 
 This seems to be a hazard as there is nothing to tell me that I have certain environment variables set. 

Alternatives I can think of to avoid this case. 

1. Put a big red banner at the top of the terminal window to mention that you are affecting a certain environment on every command you run

2. Invoke the export for the scope of a single command. Allow a command to be passed when invoking the export and only do it for the one command. This limits the scope of the export and makes it less prone to human error (this does not prevent a person from invoking a terminal, and the environment will be set for as long as the session exists should they need that). 

CC: @benders @relistan  

These are merely thoughts, but may need some consideration.

**Comment by relistan** [comment]
@frankywahl there is a reason it's called `dev:export_only` it's for development. The `README` also provides clear guidance on this issue.
