### ISSUE TITLE
Dynamic Hosts Support

### ISSUE THREAD

**Issue by laferrieren** [newrelic/centurion#146]
As of right now we have to list out the hosts that we want to deploy to.  In a lot of scenarios people that are using the cloud, might not be able to guarantee that the ip addresses of the hosts that they want to deploy to are going to be the same every time (think in the case of an autoscaling group).

I was thinking it would be a good idea to include hostgroup or host_collection option that is passed a lambda, and would return a collection of hosts.  We could then propagate :hosts in the deploy_dsl.rb after calling the lambda.  By doing it this way you wouldn't have to include specific support for any one cloud or service discover method.  But it would allow for custom tooling out of the box to support any cloud.

I am willing to work on it, I might need some help writing appropriate rspec tests.  I just wanted to get feedback first.

**Comment by relistan** [comment]
Sorry @laferrieren I'm behind on all things Centurion. How about just doing something [like I did here](https://gist.github.com/relistan/81e7b2f6c0847ae2fa8b) when you need it?
