### ISSUE TITLE
Centurion Logging Environment Variable to Stdout

### ISSUE THREAD

**Issue by yonatan-schultz** [newrelic/centurion#162]
Centurion is logging its environment variables to stdout which causes problems when integrating with tools like Jenkins since these logs are kept for a specific period and often contain secrets.

**Comment by relistan** [comment]
If your secrets are in environment variables, they are also available to anyone who has access to the Docker daemon. If you are only concerned about seeing them in jenkins, then I'd recommend running the output through a `grep -v` filter for specific environment variables. Logging the environment variables is really useful for debugging failed deploys, so turning them off entirely is not really in your best interest.
