### ISSUE TITLE
host-networked services without defined port mappings don't get health checked

### ISSUE THREAD

**Issue by intjonathan** [newrelic/centurion#164]
Services which use `network_mode: 'host'` don't need to define any port mappings, since they use the host network stack directly. However, if they don't define any mappings, they also don't have the containers checked between servers during rolling deploys. The iteration over `public_ports` [here](https://github.com/newrelic/centurion/blob/v1.8.5/lib/tasks/deploy.rake#L136) would be a no-op in that case.

The workaround would be to define a dummy port, but if you do that, the stop_container call [here](https://github.com/newrelic/centurion/blob/v1.8.5/lib/centurion/deploy.rb#L10) doesn't work, because it tries to find existing containers by public port - which it doesn't have.

**Comment by relistan** [comment]
Err that's annoying. The simplest solution would be to add a health check ports list and if it hasn't been defined, then default to the original behavior.

**Comment by intjonathan** [comment]
There's an interaction here if you specify a method as the healthcheck, perhaps the method should do its own port selections?
