### ISSUE TITLE
set :no_pull doesn't work afaik

### ISSUE THREAD

**Issue by benpillet** [newrelic/centurion#168]
I tried this:
`namespace :environment do
  task :local => :common do
    set :no_pull, true
  end
end`
but it still attempted the pull.  I ended up adding this in the task instead:
`Rake::Task["deploy:pull_image"].clear_action`
Is that the right way?

**Comment by relistan** [comment]
It _looks_ like it shoudl work by just setting it in your `common` task like you did. If that's not working, it may be a matter of the environment already being set and the top level settings being ignored. Try setting it in your `development` or `production`, etc task and see if that does it. If so, then we should fix that as it's a bug.
