### ISSUE TITLE
`deploy_console` should use `docker exec` rather than stealing a node

### ISSUE THREAD

**Issue by relistan** [newrelic/centurion#67]
Now that Docker support `docker exec` functionality, `deploy_console` should use that rather than stealing a live node from the pool to replace with a console.

**Comment by frankywahl** [comment]
I'd like to add on to that stating that now, `deploy_console` takes down all the exiting nodes before invoking the console. In the case of a UI, this take availability down which is a big issue.

**Comment by relistan** [comment]
It does not take down all the existing nodes. It takes down one of them. If you run it over and over, though, it will take down all of them. It's a bad experience that needs to be fixed now that Docker 1.5 has native `docker exec`.

**Comment by hugochinchilla** [comment]
@relistan I used deploy_console for the first time today and noticed it runs a console on all the hosts, not just the first as stated in the docs.
