### ISSUE TITLE
[Question] Why is it mandatory to have centurion in the Gemfile

### ISSUE THREAD

**Issue by zedtux** [newrelic/centurion#79]
I was wondering why do I have to have the gem on my production machines while I need it only for the deployment ?

**Comment by relistan** [comment]
Not sure what you mean?

**Comment by zedtux** [comment]
Centurion is adding the centurion gem to the Gemfile and I'm wondering why.

**Comment by relistan** [comment]
Do you mean `centurionize` does? You can move it to the development group if you'd rather.

**Comment by zedtux** [comment]
Yes it's about `centurionize`. But my question is why is it needed by centurion to be part of the Gemfile ? Does it allow the gem to do something special ?

I mean the gem is already installed on the system with `gem install centurion`. Then the gem is added to the Gemfile. I don't understand why.

**Comment by relistan** [comment]
It adds it to the Gemfile because you generally want to use `bundle exec` to run Centurion. Otherwise you have no control from inside the project as to which version of Centurion you are invoking. Using bundler makes sure you get the right one.

**Comment by zedtux** [comment]
OK I got it now. Thank you.
