### ISSUE TITLE
Centurion crashes, if keys in JSON responses from Docker API are CamelCase

### ISSUE THREAD

**Issue by toffer** [newrelic/centurion#85]
In `docker_via_api.rb`, Centurion explicitly calls v1.7 of the Docker API, which is supposed to return the JSON keys as snake_case. Using a specific version like this **should** protect us from any changes to the Docker API, like the one starting in v1.12, when the JSON keys began to be returned as CamelCase. (See [docker docs](http://docs.docker.com/reference/api/docker_remote_api/#whats-new_4))

However, when using a combination of Dogestry and Centurion, it's possible for Centurion to call v1.7 docker API endpoints and get back CamelCase, which results in Centurion crashing.

How?

When a docker image is exported from a docker host, the resulting tarball contains multiple directories, one for each layer. Each layer has a corresponding JSON file (See [docker docs for details](http://docs.docker.com/reference/api/docker_remote_api_v1.15/#load-a-tarball-with-a-set-of-images-and-tags-into-docker for details).) When the docker image is exported from a newer docker host, the keys in the JSON files are CamelCase.

Next, you import that tarball into a second docker host (using the `/images/load` API).

(Under the hood, dogestry uses these two docker API calls to export an image from one host and import it into another.)

Finally, you query the API in the second docker host for information about that image. Unfortunately, whether you use the v1.7 API, or the v1.15 API, the JSON response contains keys in CamelCase.

Here's an example of the wrong behavior:

An image (`image_1`) was exported (using `/images/(name)/get`) from a docker host with a server API of v1.12, which means that the JSON files have keys in CamelCase.

Then, we load the exported tarball (`/images/load`) into a docker host with a server API of v1.15

Now, let's hit two different versions of the API on docker host 'B'

    # [WRONG] Calling /v1.7/images/ endpoint returns CamelCase.
    # (This should return snake_case, which is all lowercase.)

    $ curl http://DOCKER_HOST_B:2375/v1.7/images/<image_1)>/json
    {"Architecture":"amd64","Author":"","Comment":"","Config":{"AttachStderr":false,...

    # [CORRECT] Calling /v1.15/images endpoint returns CamelCase

    $ curl http://DOCKER_HOST_B:2375/v1.15/images/<image_1)>/json
    {"Architecture":"amd64","Author":"","Comment":"","Config":{"AttachStderr":false,...

Interestingly enough, importing a tarball that has JSON files with keys in snake_case results in correct responses from both versions of the API. Here's an example:

An image (image_2) was exported (`/images/(name)/get`) from docker host 'A' with a server API of v1.10, which means that the JSON files have keys in snake_case.

Then, we load the exported tarball (`/images/load`) into docker host 'B' with a server API of v1.15

Again, let's hit two different versions of the API on docker host 'B'

    # [CORRECT] Calling /v1.7/images/ endpoint returns snake_case (begins with lowercase)

    $ curl http://DOCKER_HOST_B:2375/v1.7/images/<image_2>/json
    {"id":"<sha>","parent":"<sha>","created":"2015-01-08T23:15:07.130204289Z",

    # [CORRECT] Calling /v1.15/images/ endpoint returns CamelCase (begins with uppercase)

    $ curl http://DOCKER_HOST_B:2375/v1.15/images/<image_2>/json
    {"Architecture":"amd64","Author":"","Comment":"","Config":{"AttachStderr":false,...

cc: @didip @relistan @amjith

**Comment by didip** [comment]
So the solutions are:

* either to upgrade the api version and do CamelCase everywhere.

* or add extra logic to deal with both snake_case/CamelCase.

Is that right?

**Comment by toffer** [comment]
@didip Correct. I'm working on adding extra logic to handle both cases. I don't think there are too many places where I need to add it

**Comment by relistan** [comment]
That is one awesome bug report.
