### ISSUE TITLE
Choose the deploy mechanism via a CLI flag

### ISSUE THREAD

**Issue by amjith** [newrelic/centurion#86]
Now that there is Dogestry support, it would be good to have the ability to choose the means of deployment via an env var. 

This is useful as a fall back mechanism, so if S3 is unavailable then someone can fall back to using quay.io or docker hub.

**Comment by relistan** [comment]
:+1: I'd welcome a PR on that.

**Comment by relistan** [comment]
I haven't seen a driving need for this so I'm going to close it. Feel free to comment if you think this is still worthwhile.
