### ISSUE TITLE
[Question]  Production code deployment

### ISSUE THREAD

**Issue by sauravyadav** [newrelic/centurion#91]
Is there any way to roll back the changes?

Is there any way to do the zero downtime deployment with or without rolling releases?

**Comment by relistan** [comment]
Rollback is by redeploying your previous tag. Use the `-t` or `--tag` option. Zero downtime deployment via rolling deployments is explained in the README. You need to provide a few configuration options and tune them for your load balancer check intervals. We do zero downtime deploys 100% of the time.
