### ISSUE TITLE
Centurion config: tag to deploy for a specific environment

### ISSUE THREAD

**Issue by bettse** [newrelic/centurion#98]
Currently the command line interface for centurion will deploy either the provided tag, or default to 'latest'.  For teams using CI, this becomes problematic when latest points to a potentially unstable image.  This isn't a problem for anyone already familiar with the tags used by the team, but if a secondary team (DevOps, SRE, hosting, etc) need to deploy, they wouldn't know what tag to use.  

My idea is to add a config value that allows each environment to optionally specify the tag that should be used if no tag is provided on the command line.  This also leaves the flexibility for a team to have a deploy tag name that may not match the environment name for historical reasons.  If no deploy tag is specified in the config, and none is provided on the command line, centurion could continue to use 'latest' as before.

**Comment by relistan** [comment]
This could be done. It would require setting a default much deeper down than we do now. But we could do that. You could also implement this yourself in your Rake file for the affected project with something like this in each environment:

```ruby
if fetch(:tag) == 'latest'
  set :tag, 'my_awesome_tag'
end
```
This would preclude using the `latest` tag at all in your project, however.

**Comment by bettse** [comment]
I hadn't considered(or realized we could) embedding ruby into the config, but that would certainly solve the problem easily.  I'll give that a try.

**Comment by relistan** [comment]
I don't recommend putting much Ruby in there, but that's a wee few lines. :)

**Comment by bettse** [comment]
For future reference, this is already possible using `set :tag ''` in the config, per https://github.com/newrelic/centurion/blob/3f293d9fc0528a3c562a6fb86c8b8d43d9a0b426/bin/centurion#L29
